/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author rikiz
 */
public class JDlgRdpProdutos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgRdpProdutos.class.getName());

    /**
     * Creates new form JDlgRdpProdutos
     */
    public JDlgRdpProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
            setTitle("Loja de Roupas do Rick - Produtos");
            setLocationRelativeTo(null);
            jTxtRdpCategoria.setEnabled(false);
            jTxtRdpCodigoProduto.setEnabled(false);
            jTxtRdpDescricao.setEnabled(false);
            jTxtRdpMarca.setEnabled(false);
            jTxtRdpNomeProduto.setEnabled(false);
            jCboRdpTamanho.setEnabled(false);
            jTxtRdpPreco.setEnabled(false);
            jBtnRdpCancelar.setEnabled(false);
            jBtnRdpConfirmar.setEnabled(false);
            jBtnRdpAlterar.setEnabled(true);
            jBtnRdpExcluir.setEnabled(true);
            jBtnRdpIncluir.setEnabled(true);
            jBtnRdpPesquisar.setEnabled(true);
        
    }
    
      public void habilitar(){
            jTxtRdpCategoria.setEnabled(true);
            jTxtRdpCodigoProduto.setEnabled(true);
            jTxtRdpDescricao.setEnabled(true);
            jTxtRdpMarca.setEnabled(true);
            jTxtRdpNomeProduto.setEnabled(true);
            jCboRdpTamanho.setEnabled(true);
            jTxtRdpPreco.setEnabled(true);
            jBtnRdpCancelar.setEnabled(true);
            jBtnRdpConfirmar.setEnabled(true);
            jBtnRdpAlterar.setEnabled(false);
            jBtnRdpExcluir.setEnabled(false);
            jBtnRdpIncluir.setEnabled(false);
            jBtnRdpPesquisar.setEnabled(false); 
    }

        public void desabilitar(){
            jTxtRdpCategoria.setEnabled(false);
            jTxtRdpCodigoProduto.setEnabled(false);
            jTxtRdpDescricao.setEnabled(false);
            jTxtRdpMarca.setEnabled(false);
            jTxtRdpNomeProduto.setEnabled(false);
            jCboRdpTamanho.setEnabled(false);
            jTxtRdpPreco.setEnabled(false);
            jBtnRdpCancelar.setEnabled(false);
            jBtnRdpConfirmar.setEnabled(false);
            jBtnRdpAlterar.setEnabled(true);
            jBtnRdpExcluir.setEnabled(true);
            jBtnRdpIncluir.setEnabled(true);
            jBtnRdpPesquisar.setEnabled(true);    
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtRdpNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtRdpCodigoProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtRdpCategoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCboRdpTamanho = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtRdpPreco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtRdpMarca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtRdpDescricao = new javax.swing.JTextField();
        jBtnRdpConfirmar = new javax.swing.JButton();
        jBtnRdpCancelar = new javax.swing.JButton();
        jBtnRdpPesquisar = new javax.swing.JButton();
        jBtnRdpIncluir = new javax.swing.JButton();
        jBtnRdpAlterar = new javax.swing.JButton();
        jBtnRdpExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome do Produto");

        jLabel2.setText("Codigo");

        jLabel3.setText("Categoria");

        jLabel4.setText("Tamanho");

        jCboRdpTamanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Preço");

        jLabel6.setText("Marca");

        jLabel7.setText("Descrição");

        jBtnRdpConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnRdpConfirmar.setText("Confirmar");
        jBtnRdpConfirmar.addActionListener(this::jBtnRdpConfirmarActionPerformed);

        jBtnRdpCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnRdpCancelar.setText("Cancelar");
        jBtnRdpCancelar.addActionListener(this::jBtnRdpCancelarActionPerformed);

        jBtnRdpPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnRdpPesquisar.setText("Pesquisar");

        jBtnRdpIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnRdpIncluir.setText("Incluir");
        jBtnRdpIncluir.addActionListener(this::jBtnRdpIncluirActionPerformed);

        jBtnRdpAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnRdpAlterar.setText("Alterar");

        jBtnRdpExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnRdpExcluir.setText("Excluir");
        jBtnRdpExcluir.addActionListener(this::jBtnRdpExcluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(147, 147, 147)
                                .addComponent(jLabel2)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel3)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtRdpDescricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTxtRdpPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                            .addComponent(jTxtRdpNomeProduto, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTxtRdpMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTxtRdpCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTxtRdpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCboRdpTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnRdpIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRdpAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnRdpExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnRdpConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRdpCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRdpPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboRdpTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRdpDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRdpIncluir)
                    .addComponent(jBtnRdpAlterar)
                    .addComponent(jBtnRdpExcluir)
                    .addComponent(jBtnRdpConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRdpCancelar)
                    .addComponent(jBtnRdpPesquisar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRdpConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpConfirmarActionPerformed

    private void jBtnRdpCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpCancelarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpCancelarActionPerformed

    private void jBtnRdpIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpIncluirActionPerformed

    private void jBtnRdpExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpExcluirActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnRdpExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgRdpProdutos dialog = new JDlgRdpProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRdpAlterar;
    private javax.swing.JButton jBtnRdpCancelar;
    private javax.swing.JButton jBtnRdpConfirmar;
    private javax.swing.JButton jBtnRdpExcluir;
    private javax.swing.JButton jBtnRdpIncluir;
    private javax.swing.JButton jBtnRdpPesquisar;
    private javax.swing.JComboBox<String> jCboRdpTamanho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTxtRdpCategoria;
    private javax.swing.JTextField jTxtRdpCodigoProduto;
    private javax.swing.JTextField jTxtRdpDescricao;
    private javax.swing.JTextField jTxtRdpMarca;
    private javax.swing.JTextField jTxtRdpNomeProduto;
    private javax.swing.JTextField jTxtRdpPreco;
    // End of variables declaration//GEN-END:variables
}
