/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author rikiz
 */
public class JDlgRdpFornecedor extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDlgRdpFornecedor.class.getName());

    /**
     * Creates new form JDlgRdpFornecedor
     */
    public JDlgRdpFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
          setTitle("Loja de Roupas do Rick - Fornecedor");
            setLocationRelativeTo(null);
            jTxtRdpCep.setEnabled(false);
            jTxtRdpCidade.setEnabled(false);
            jTxtRdpEmail.setEnabled(false);
            jTxtRdpId.setEnabled(false);
            jTxtRdpNumero.setEnabled(false);
            jTxtRdpTelefone.setEnabled(false);
            jTxtRdpEndereco.setEnabled(false);
            jTxtRdpCnpj.setEnabled(false);
            jTxtRdpInscricaoEstadual.setEnabled(false);
            jTxtRdpNomeEmpresa.setEnabled(false);
            jTxtRdpNomeFantasia.setEnabled(false);
            jTxtRdpResponsavel.setEnabled(false);
            jTxtRdpUf.setEnabled(false);
            jTxtRdpWhats.setEnabled(false);
            jChbRdpAtivo.setEnabled(false);
            jBtnRdpCancelar.setEnabled(false);
            jBtnRdpConfirmar.setEnabled(false);
            jBtnRdpAlterar.setEnabled(true);
            jBtnRdpExcluir.setEnabled(true);
            jBtnRdpIncluir.setEnabled(true);
            jBtnRdpPesquisar.setEnabled(true);
    }
  public void habilitar(){
               jTxtRdpCep.setEnabled(true);
            jTxtRdpCidade.setEnabled(true);
            jTxtRdpEmail.setEnabled(true);
            jTxtRdpId.setEnabled(true);
            jTxtRdpNumero.setEnabled(true);
            jTxtRdpTelefone.setEnabled(true);
            jTxtRdpEndereco.setEnabled(true);
            jTxtRdpCnpj.setEnabled(true);
            jTxtRdpInscricaoEstadual.setEnabled(true);
            jTxtRdpNomeEmpresa.setEnabled(true);
            jTxtRdpNomeFantasia.setEnabled(true);
            jTxtRdpResponsavel.setEnabled(true);
            jTxtRdpUf.setEnabled(true);
            jTxtRdpWhats.setEnabled(true);
            jChbRdpAtivo.setEnabled(true);
            jBtnRdpCancelar.setEnabled(true);
            jBtnRdpConfirmar.setEnabled(true);
            jBtnRdpAlterar.setEnabled(false);
            jBtnRdpExcluir.setEnabled(false);
            jBtnRdpIncluir.setEnabled(false);
            jBtnRdpPesquisar.setEnabled(false); 
       }
  
   public void desabilitar(){
              jTxtRdpCep.setEnabled(false);
            jTxtRdpCidade.setEnabled(false);
            jTxtRdpEmail.setEnabled(false);
            jTxtRdpId.setEnabled(false);
            jTxtRdpNumero.setEnabled(false);
            jTxtRdpTelefone.setEnabled(false);
            jTxtRdpEndereco.setEnabled(false);
            jTxtRdpCnpj.setEnabled(false);
            jTxtRdpInscricaoEstadual.setEnabled(false);
            jTxtRdpNomeEmpresa.setEnabled(false);
            jTxtRdpNomeFantasia.setEnabled(false);
            jTxtRdpResponsavel.setEnabled(false);
            jTxtRdpUf.setEnabled(false);
            jTxtRdpWhats.setEnabled(false);
            jChbRdpAtivo.setEnabled(false);
            jBtnRdpCancelar.setEnabled(false);
            jBtnRdpConfirmar.setEnabled(false);
            jBtnRdpAlterar.setEnabled(true);
            jBtnRdpExcluir.setEnabled(true);
            jBtnRdpIncluir.setEnabled(true);
            jBtnRdpPesquisar.setEnabled(true);
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtRdpId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtRdpNomeEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtRdpNomeFantasia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtRdpCnpj = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtRdpInscricaoEstadual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtRdpResponsavel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtRdpTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTxtRdpWhats = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtRdpEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtRdpCep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtRdpEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtRdpNumero = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtRdpCidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtRdpUf = new javax.swing.JTextField();
        jChbRdpAtivo = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jBtnRdpIncluir = new javax.swing.JButton();
        jBtnRdpAlterar = new javax.swing.JButton();
        jBtnRdpExcluir = new javax.swing.JButton();
        jBtnRdpConfirmar = new javax.swing.JButton();
        jBtnRdpCancelar = new javax.swing.JButton();
        jBtnRdpPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("Nome da Empresa");

        jLabel3.setText("Nome Fantasia");

        jLabel4.setText("CNPJ");

        jLabel5.setText("Inscrição Estadual");

        jLabel6.setText("Responsável");

        jLabel7.setText("Telefone");

        jLabel8.setText("Whatsapp");

        jLabel9.setText("Email");

        jLabel10.setText("CEP");

        jLabel11.setText("Endereço");

        jLabel12.setText("Número");

        jLabel13.setText("Cidade");

        jLabel14.setText("UF");

        jChbRdpAtivo.setText("Ativo");

        jLabel15.setText("Status");

        jBtnRdpIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnRdpIncluir.setText("Incluir");
        jBtnRdpIncluir.addActionListener(this::jBtnRdpIncluirActionPerformed);

        jBtnRdpAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnRdpAlterar.setText("Alterar");

        jBtnRdpExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnRdpExcluir.setText("Excluir");
        jBtnRdpExcluir.addActionListener(this::jBtnRdpExcluirActionPerformed);

        jBtnRdpConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnRdpConfirmar.setText("Confirmar");
        jBtnRdpConfirmar.addActionListener(this::jBtnRdpConfirmarActionPerformed);

        jBtnRdpCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnRdpCancelar.setText("Cancelar");
        jBtnRdpCancelar.addActionListener(this::jBtnRdpCancelarActionPerformed);

        jBtnRdpPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnRdpPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtRdpEndereco)
                                .addComponent(jTxtRdpInscricaoEstadual)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTxtRdpId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtRdpNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtRdpWhats))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtRdpNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtRdpCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTxtRdpUf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jChbRdpAtivo))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtRdpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTxtRdpCep))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtRdpNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTxtRdpCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jTxtRdpResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jTxtRdpTelefone))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel13)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtnRdpIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRdpAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnRdpExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRdpConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRdpCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRdpPesquisar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpWhats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRdpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtRdpUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbRdpAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRdpIncluir)
                    .addComponent(jBtnRdpAlterar)
                    .addComponent(jBtnRdpExcluir)
                    .addComponent(jBtnRdpConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRdpCancelar)
                    .addComponent(jBtnRdpPesquisar))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRdpIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpIncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpIncluirActionPerformed

    private void jBtnRdpExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpExcluirActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnRdpExcluirActionPerformed

    private void jBtnRdpConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpConfirmarActionPerformed

    private void jBtnRdpCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRdpCancelarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnRdpCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDlgRdpFornecedor dialog = new JDlgRdpFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRdpAlterar;
    private javax.swing.JButton jBtnRdpCancelar;
    private javax.swing.JButton jBtnRdpConfirmar;
    private javax.swing.JButton jBtnRdpExcluir;
    private javax.swing.JButton jBtnRdpIncluir;
    private javax.swing.JButton jBtnRdpPesquisar;
    private javax.swing.JCheckBox jChbRdpAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtRdpCep;
    private javax.swing.JTextField jTxtRdpCidade;
    private javax.swing.JTextField jTxtRdpCnpj;
    private javax.swing.JTextField jTxtRdpEmail;
    private javax.swing.JTextField jTxtRdpEndereco;
    private javax.swing.JTextField jTxtRdpId;
    private javax.swing.JTextField jTxtRdpInscricaoEstadual;
    private javax.swing.JTextField jTxtRdpNomeEmpresa;
    private javax.swing.JTextField jTxtRdpNomeFantasia;
    private javax.swing.JTextField jTxtRdpNumero;
    private javax.swing.JTextField jTxtRdpResponsavel;
    private javax.swing.JTextField jTxtRdpTelefone;
    private javax.swing.JTextField jTxtRdpUf;
    private javax.swing.JTextField jTxtRdpWhats;
    // End of variables declaration//GEN-END:variables
}
